//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SuperMSoftware.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class bills
    {
        public int bill_id { get; set; }
        public int employee_id { get; set; }
        public string bill_date { get; set; }
        public int total_amount { get; set; }
    
        public virtual employees employees { get; set; }
    }
}
