//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SuperMSoftware.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class products
    {
        public int product_id { get; set; }
        public string product_name { get; set; }
        public int stock { get; set; }
        public int price { get; set; }
        public int category_id { get; set; }
    
        public virtual categories categories { get; set; }
    }
}
